-- Haskell module generated by the BNF converter

module Sum.Skel where

import qualified Sum.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transExp :: Sum.Abs.Exp -> Result
transExp x = case x of
  Sum.Abs.EInt integer -> failure x
  Sum.Abs.EPlus exp integer -> failure x

